### ISSUE TITLE
Can't import read_until

### ISSUE THREAD

**Issue by emilhaegglund** [mattloose/RUscripts#2]
Can't import ReadUntil from read_until when running gReadUntil.py, seems like read_until.py is missing in the repository.

**Comment by mattloose** [comment]
This is intentional. read_until.py is a component of the Oxford Nanopore Read Until API - this has to be obtained directly from Oxford Nanopore and is not provided by these scripts.

Please see this section of the documentation for details:
http://mattloose.github.io/RUscriptsdocs/install/#obtaining-the-read-until-api

**Comment by Runsheng** [comment]
Would you please share some knowledge on how to get the read_until API on minKNOW >1.5 now? I can find some scripts like "test_read_until*.py" in the ont_python folder, but not the "read_until.py". 

The Nanopore wiki forum has been changed, so the only way to get the API is to contact the ONT help mail directly?

Many thanks and best regards,
Runsheng

**Comment by mattloose** [comment]
You need to contact Ont to get access to the api. 

However you should note that as of today there are issues with the api which are disrupting the function of read until.

**Comment by Runsheng** [comment]
Thank you! I will try.
